### ISSUE TITLE
Scss系の変数, funciton, mixin などを整理する

### ISSUE THREAD

**Issue by kitamuraDev** [kitamuraDev/site-clone-with-sass#3]
## ディレクトリ構成

```
- scss
  - index.scss
  - _global.scss
  - _functions.scss
  - _mediaquery.scss
```

### index.scss

```scss
@charset "UTF-8";

// 分割された .scss ファイルを読み込む
@import 'xxx';
```

### _functions.scss

```scss
// example - rem(24) => 1.5rem
@function rem($fontSize) {
  @return ($fontSize / 16) * 1rem;
}
```

### _mediaquery.scss

```scss
$sp: 560px;

@mixin sp {
  @media screen and (max-width: ($sp)) {
    @content;
  }
}

// 複数のブレークポイントを管理する場合
// $breakpoints: (
//   'sp': 'screen and (max-width: 560px)',
// ) !default;

// @mixin mq($breakpoint) {
//   @media #{map-get($breakpoints, $breakpoint)} {
//     @content;
//   }
// }
```

### _global.scss

```scss
// カラーパレット
$color_dark: #333 !default;
$color_light: #fafafa !default;

// 背景色
$bg_color_base: $color_light !default;

// テキストカラー
$text_color_base: $color_dark !default;

// フォントファミリー
$font_family_serif: 'Noto Serif JP', serif !default;

// フォントサイズ
$font_size_xs: rem(12);
$font_size_s: rem(14);
$font_size_md: rem(16);
$font_size_lg: rem(18);
$font_size_xl: rem(24);

// 行間
$line_height_s: 1.15 !default;
$line_height_md: 1.5 !default;
$line_height_lg: 1.75 !default;
$line_height_xl: 2 !default;
$line_height_default: $lineHeight_middle !default;
```
